#!/bin/bash

set -eEuo pipefail

shopt -s checkwinsize; (:;:)

sleep "${2:-.2}"
((total=COLUMNS-4))
((progress=$1*total/100))

if (( $1 > 68 )); then
  color=2
elif (( $1 > 34 )); then
  color=3
fi

printf '\r|\e[4%dm%*s\e[m' "${color:-1}" "$progress"
printf '\e[%dG|%d%%' "$total" "$1"

(( $1 == 100 ))&& printf '\n'
